# Variable de config de l'app
apiVersion: v1
kind: ConfigMap
metadata:
  name: librak8s-api-config
  namespace: back
data:
  DB_URL: "jdbc:postgresql://librak8s-db.postgres.database.azure.com:5432/librak8s?sslmode=require&channelBinding=require"
  DB_USER: "librak8s"
  DB_HOST: "librak8s-db.default.svc.cluster.local"