apiVersion: apps/v1
kind:       Deployment
metadata:
  name:      librak8s-api
  namespace: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: librak8s-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge:       1
  template:
    metadata:
      labels:
        app: librak8s-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name:            api
          image:           __ACR_SERVER__/librak8s-backend:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: librak8s-api-config

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: librak8s-api-secret
                  key:  DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: librak8s-api-secret
                  key:  JWT_SECRET


          resources:
            requests:
              memory: "256Mi"
              cpu:    "250m"
            limits:
              memory: "512Mi"
              cpu:    "500m"

              # Readiness : prêt à recevoir du trafic ?
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds:       5
            failureThreshold:    3

            # Liveness : encore en vie ? (sinon kubelet redémarre)
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds:       10
            failureThreshold:    3