apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librak8s-pvc
  namespace: back
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      name: librak8s-pv