apiVersion: v1
kind:       Secret
metadata:
  name:     librak8s-api-secret
  namespace: back
type: Opaque
data:
  DB_PASSWORD: bnBnX0NnY0I1OE1Yc2hlUQ==
  JWT_SECRET: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==