apiVersion: v1
kind:       Service
metadata:
  name:      librak8s-api-service
  namespace: back
spec:
  type: ClusterIP
  selector:
    app: librak8s-api
  ports:
    - name:       http
      port:       80     # port exposé dans le cluster
      targetPort: 8080  # port du container Spring Boot