name: Deploy — Ingress

on:
  push:
    branches: [develop]
    paths:
      - 'k8s/**'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: |
          az aks get-credentials --resource-group librak8s-rg --name librak8s-aks \
            --overwrite-existing

      - run: kubectl apply -f k8s/